# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master , develop , feature/** ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos64-latest, macos32-latest, ubuntu-arm-latest, ubuntu64-latest, ubuntu32-latest, windows-latest, ubuntu-20.04, ubuntu-16.04]
        include:
        - os: macos64-latest
          TARGET: x86_64-apple-darwin
          COMPILER: clang
          LINKER: clang
          
        - os: macos32-latest
          TARGET: x86_32-apple-darwin
          COMPILER: clang
          LINKER: clang

        - os: ubuntu-arm-latest
          TARGET: armv7-unknown-linux-musleabihf
          COMPILER: arm-linux-gnueabihf-gcc-5
          LINKER: gcc-5-arm-linux-gnueabihf

        - os: ubuntu64-latest
          TARGET: x86_64-unknown-linux-musl
          COMPILER: gcc
          LINKER: gcc
        
        - os: ubuntu32-latest
          TARGET: x86_32-unknown-linux-musl
          COMPILER: gcc
          LINKER: gcc

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml -DskipTests
